- hosts: servers
  become: yes
  tasks:
    - name: Add Erlang key
      become: true
      become_user: ubuntu
      shell: wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo apt-key add -

    - name: Add Erlang repo
      become: true
      become_user: ubuntu
      shell: echo "deb https://packages.erlang-solutions.com/ubuntu bionic contrib" | sudo tee /etc/apt/sources.list.d/rabbitmq.list      

    - name: Install Erlang
      apt:
        name: erlang
        state: present
        update_cache: true
    
    - name: Add RabbitMQ repo
      become: true
      become_user: ubuntu
      shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash

    - name: Install RabbitMQ
      become: true
      apt:
        name: rabbitmq-server
        state: present
        update_cache: true
