- hosts: servers
  become: yes
  tasks:
    - name: Create Zookeeper config
      copy:
        dest: "/etc/systemd/system/zookeeper.service"
        content: |
          [Unit]
          Description=Apache Zookeeper server
          Documentation=http://zookeeper.apache.org
          Requires=network.target remote-fs.target
          After=network.target remote-fs.target

          [Service]
          Type=simple
          ExecStart=/usr/local/kafka/bin/zookeeper-server-start.sh /usr/local/kafka/config/zookeeper.properties
          ExecStop=/usr/local/kafka/bin/zookeeper-server-stop.sh
          Restart=on-abnormal

          [Install]
          WantedBy=multi-user.target

    - name: Create Kafka config
      copy:
        dest: "/etc/systemd/system/kafka.service"
        content: |
          [Unit]
          Description=Apache Kafka Server
          Documentation=http://kafka.apache.org/documentation.html
          Requires=zookeeper.service

          [Service]
          Type=simple
          Environment="JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"
          ExecStart=/usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties
          ExecStop=/usr/local/kafka/bin/kafka-server-stop.sh

          [Install]
          WantedBy=multi-user.target

    - name: Save config
      become: true
      become_user: ubuntu
      shell: sudo systemctl daemon-reload

    - name: Start Zookeeper
      become: true
      become_user: ubuntu
      shell: sudo systemctl start zookeeper

    - name: Start Kafka
      become: true
      become_user: ubuntu
      shell: sudo systemctl start kafka
