- hosts: servers
  become: yes
  tasks:
    - name: Install Java
      apt:
        name: default-jdk
        state: present
        update_cache: true

    - name: Download Kafka
      become: true
      become_user: ubuntu
      shell: cd ~ && wget https://mirrors.ukfast.co.uk/sites/ftp.apache.org/kafka/2.7.0/kafka_2.13-2.7.0.tgz
    
    - name: Unzip package
      become: true
      become_user: ubuntu
      shell: cd ~ && tar xzf kafka_2.13-2.7.0.tgz

    - name: Move to Kafka directory
      become: true
      become_user: ubuntu
      shell: cd ~ && sudo mv kafka_2.13-2.7.0 /usr/local/kafka

