- hosts: servers
  become: yes
  tasks:
    - name: Create MongoDB Db and user
      shell: |
        mongosh admin --username superuser --password mongo --eval 'db.createUser({user: "testuser", pwd: "mongo", roles: [{role: "readWrite", db: "test-db"}]})'
