- hosts: servers
  become: yes
  tasks:
    - name: Add dependencies
      apt:
        name: ['curl', 'gnupg']
        state: present
        update_cache: true

    - name: Add MongoDB key
      become: true
      become_user: ubuntu
      shell: curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor

    - name: Add MongoDB repo
      become: true
      become_user: ubuntu
      shell: echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
      
    - name: Install MongoDB
      apt:
        name: ['mongodb-org']
        state: present
        update_cache: true

    - name: Ensure the MongoDB service is running
      service: name=mongod state=started enabled=yes
